version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
     environment:
      DBURL: ep-morning-sun-a2z0wnt0.eu-central-1.pg.koyeb.app
      DBNAME: koyebdb
      DBUSERNAME: koyeb-adm
      DBPASSWORD: npg_Xn1EDclk6qRb
